settingsVersion: 2
graphics:
  defaultQuality: High
  presets:
    Ultra:
      resolutionFactor: 1
      fpsCap: 120
      msaaSamples: 8
      shadowQuality: High
      shadowBias: 0
      shadowCascadeCount: 4
      shadowCascadeResolutions:
      - 4096
      - 2048
      - 2048
      - 1024
      supportSoftShadows: true
      cloudsResolutionMultiplier: 1
      skyResolution: 512
      vegetationInstanceBudget: 65536
      lodBias: -1
      maxGiProbeStatesPerSnapshot: 4
    High:
      resolutionFactor: 1
      fpsCap: 120
      msaaSamples: 4
      shadowQuality: High
      shadowBias: 0
      shadowCascadeCount: 4
      shadowCascadeResolutions:
      - 2048
      - 2048
      - 1024
      - 1024
      supportSoftShadows: true
      cloudsResolutionMultiplier: 0.75
      skyResolution: 256
      vegetationInstanceBudget: 32768
      lodBias: 0
      maxGiProbeStatesPerSnapshot: 3
    Medium:
      resolutionFactor: 0.85
      fpsCap: 120
      msaaSamples: 2
      shadowQuality: Medium
      shadowBias: 0
      shadowCascadeCount: 3
      shadowCascadeResolutions:
      - 2048
      - 1024
      - 512
      supportSoftShadows: true
      cloudsResolutionMultiplier: 0.5
      skyResolution: 256
      vegetationInstanceBudget: 16384
      lodBias: 0
      maxGiProbeStatesPerSnapshot: 2
    Low:
      resolutionFactor: 0.7
      fpsCap: 120
      msaaSamples: 1
      shadowQuality: Low
      shadowBias: 0
      shadowCascadeCount: 2
      shadowCascadeResolutions:
      - 1024
      - 512
      supportSoftShadows: false
      cloudsResolutionMultiplier: 0.5
      skyResolution: 128
      vegetationInstanceBudget: 8192
      lodBias: 1
      maxGiProbeStatesPerSnapshot: 2
    VeryLow:
      resolutionFactor: 0.5
      fpsCap: 120
      msaaSamples: 1
      shadowQuality: VeryLow
      shadowBias: 0
      shadowCascadeCount: 1
      shadowCascadeResolutions:
      - 512
      supportSoftShadows: false
      cloudsResolutionMultiplier: 0.125
      skyResolution: 64
      vegetationInstanceBudget: 2048
      lodBias: 2
      maxGiProbeStatesPerSnapshot: 1
...
