#include "AssetRegistry/Shader/ShaderCompiler.h"

#include "AssetRegistry/FileId.h"
#include "AssetRegistry/AssetRegistry.h"
#include "AssetRegistry/Texture/TextureImporter.h"
#include "YamlExceptionBoundary.h"

#include "ShaderAssetInfo.h"
#include "ShaderCache.h"
#include "ShaderYamlIncludeResolver.h"
#include "RHI/Shader.h"
#include "Core/Utils.h"
#include <atomic>
#include <cctype>
#include <filesystem>
#include <fstream>
#include <algorithm>
#include <iostream>
#include <iterator>
#include <limits>
#include <memory>

#include "Core/YamlSerializable.h"
#include <shaderc/shaderc.hpp>
#include <thread>
#include <mutex>

#include "Containers/Set.h"
#include "Tasks/Tasks.h"
#include "Tasks/Scheduler.h"

#include "FrameGraph/LightCullingNode.h"
#include "FrameGraph/ShadowPrepassNode.h"

#include "RHI/VertexDescription.h"

#include "ECS/LightingECS.h"

using namespace Sailor;

namespace
{
	template<typename TMap, typename TKey>
	class TConcurrentMapEntryUnlockGuard final
	{
	public:
		TConcurrentMapEntryUnlockGuard(TMap& map, const TKey& key) noexcept :
			m_map(map),
			m_key(key)
		{
		}

		~TConcurrentMapEntryUnlockGuard() noexcept
		{
			m_map.Unlock(m_key);
		}

		TConcurrentMapEntryUnlockGuard(const TConcurrentMapEntryUnlockGuard&) = delete;
		TConcurrentMapEntryUnlockGuard& operator=(const TConcurrentMapEntryUnlockGuard&) = delete;

	private:
		TMap& m_map;
		const TKey& m_key;
	};

	void TrackAssetProcessing(
		const AssetRegistry::AssetProcessingToken& token,
		const Tasks::TaskPtr<bool>& processingTask)
	{
		AssetRegistry* assetRegistry = App::GetSubmodule<AssetRegistry>();
		if (assetRegistry == nullptr)
		{
			return;
		}
		assetRegistry->TrackScanProcessingTask(processingTask);
		if (!token)
		{
			return;
		}
		if (!processingTask)
		{
			assetRegistry->CompleteAssetProcessing(token, false);
			return;
		}

		Tasks::TaskPtr<bool> acknowledgementTask = Tasks::CreateTaskWithResult<bool>(
			"Acknowledge Asset Processing",
			[token, processingTask]()
			{
				const bool bSucceeded = processingTask->GetResult();
				if (AssetRegistry* currentRegistry = App::GetSubmodule<AssetRegistry>())
				{
					currentRegistry->CompleteAssetProcessing(token, bSucceeded);
				}
				return bSucceeded;
			});
		// Join provides the synchronization boundary before GetResult(). Using a
		// continuation here can race Task::Then's eager result handoff.
		acknowledgementTask->Join(processingTask);
		acknowledgementTask->Run();
	}
}

bool ShaderSet::IsReady() const
{
	return ((m_rhiVertexShader && m_rhiFragmentShader) || m_rhiComputeShader) &&
		((m_rhiVertexShaderDebug && m_rhiFragmentShaderDebug) || m_rhiComputeShaderDebug);
}

void ShaderAsset::Deserialize(const YAML::Node& inData)
{
	DESERIALIZE_PROPERTY(inData, m_glslVertex);
	DESERIALIZE_PROPERTY(inData, m_glslFragment);
	DESERIALIZE_PROPERTY(inData, m_glslCompute);
	DESERIALIZE_PROPERTY(inData, m_glslCommon);
	DESERIALIZE_PROPERTY(inData, m_defines);
	DESERIALIZE_PROPERTY(inData, m_includes);
	DESERIALIZE_PROPERTY(inData, m_colorAttachments);
	DESERIALIZE_PROPERTY(inData, m_depthStencilAttachment);
}

ShaderCompiler::ShaderCompiler(ShaderAssetInfoHandler* infoHandler)
{
	SAILOR_PROFILE_FUNCTION();
	m_allocator = ObjectAllocatorPtr::Make(EAllocationPolicy::SharedMemory_MultiThreaded);
	m_shaderCache.Initialize();
	infoHandler->Subscribe(this);
	App::GetSubmodule<AssetRegistry>()->SubscribeContentChanges(this);

	UpdateConstantsLibrary();

	TVector<FileId> shaderAssetInfos;
	App::GetSubmodule<AssetRegistry>()->GetAllAssetInfos<ShaderAssetInfo>(shaderAssetInfos);

	if (bShouldAutoCompileAllPermutations)
	{
		for (const auto& uid : shaderAssetInfos)
		{
			CompileAllPermutations(uid);
		}
	}
}

ShaderCompiler::~ShaderCompiler()
{
	if (AssetRegistry* assetRegistry = App::GetSubmodule<AssetRegistry>())
	{
		assetRegistry->UnsubscribeContentChanges(this);
	}

	for (auto& shaders : m_loadedShaders)
	{
		for (auto& shader : shaders.m_second)
		{
			shader.m_second.DestroyObject(m_allocator);
		}
	}

	m_shaderCache.Shutdown();
}

std::string GenerateConstantsLibrary(uint32_t version)
{
	std::stringstream stream;

	stream << "/*" << version << "*/" << "\n";
	stream << "// Code is generated by Sailor Engine" << "\n";

	stream << "\n" << "// Vertex Attributes" << "\n";
	stream << "#define DefaultPositionBinding " << RHI::RHIVertexDescription::DefaultPositionBinding << "\n";
	stream << "#define DefaultNormalBinding " << RHI::RHIVertexDescription::DefaultNormalBinding << "\n";
	stream << "#define DefaultTexcoordBinding " << RHI::RHIVertexDescription::DefaultTexcoordBinding << "\n";
	stream << "#define DefaultColorBinding " << RHI::RHIVertexDescription::DefaultColorBinding << "\n";
	stream << "#define DefaultTangentBinding " << RHI::RHIVertexDescription::DefaultTangentBinding << "\n";
	stream << "#define DefaultBitangentBinding " << RHI::RHIVertexDescription::DefaultBitangentBinding << "\n";
	stream << "#define DefaultBoneIdsBinding " << RHI::RHIVertexDescription::DefaultBoneIdsBinding << "\n";
	stream << "#define DefaultBoneWeightsBinding " << RHI::RHIVertexDescription::DefaultBoneWeightsBinding << "\n";

	stream << "\n" << "// Tile Lighting" << "\n";
	stream << "#define LIGHTS_CULLING_TILE_SIZE " << LightCullingNode::TileSize << "\n";
	stream << "#define LIGHTS_CANDIDATES_PER_TILE " << 196 << "\n";
	stream << "#define LIGHTS_PER_TILE " << LightCullingNode::LightsPerTile << "\n";

	stream << "\n" << "// GPU Culling" << "\n";
	stream << "#define GPU_CULLING_GROUP_SIZE " << RHI::Renderer::GPUCullingGroupSize << "\n";


	stream << "\n" << "// Shadows" << "\n";
	stream << "#define MAX_SHADOWS_IN_VIEW " << LightingECS::MaxShadowsInView << "\n";
	stream << "#define MAX_TEXTURES_IN_SCENE " << TextureImporter::MaxTexturesInScene << "\n";
	stream << "#define NUM_CSM_CASCADES " << LightingECS::NumCascades << "\n";
	stream << "const float ShadowCascadeLevels[" << LightingECS::NumCascades << "] = { ";

	for (uint32_t i = 0; i < LightingECS::NumCascades; i++)
	{
		stream << LightingECS::ShadowCascadeLevels[i];

		if (i != LightingECS::NumCascades - 1)
		{
			stream << ",";
		}
	}

	stream << "}; \n";

	return stream.str();
}

void ShaderCompiler::UpdateConstantsLibrary()
{
	// Generated engine shader ABI belongs to Engine Content. A distinct workspace
	// consumes that read-only library through the shared virtual content mount and
	// must never create a higher-priority local override.
	if (!App::GetWorkspaceContext().IsEngineMode())
	{
		return;
	}

	std::filesystem::path constantsLibrary;
	if (!App::GetSubmodule<AssetRegistry>()->ResolveWorkspaceContentPathForWrite(
			"Shaders/Constants.glsl",
			constantsLibrary))
	{
		SAILOR_LOG_ERROR("Cannot resolve the writable Engine shader constants library path.");
		return;
	}
	std::filesystem::create_directories(constantsLibrary.parent_path());
	if (!std::filesystem::exists(constantsLibrary))
	{
		std::ofstream assetFile(constantsLibrary);
		assetFile << GenerateConstantsLibrary(CacheProducerVersion);
		assetFile.close();

		return;
	}

	std::ifstream assetFile(constantsLibrary, std::ios::binary);
	const std::string currentLibrary{
		std::istreambuf_iterator<char>(assetFile),
		std::istreambuf_iterator<char>()};
	assetFile.close();

	const std::string generatedLibrary = GenerateConstantsLibrary(CacheProducerVersion);
	if (currentLibrary != generatedLibrary)
	{
		std::ofstream assetFile(constantsLibrary, std::ios::binary | std::ios::trunc);
		assetFile << generatedLibrary;
		assetFile.close();
	}
}

bool ShaderCompiler::GeneratePrecompiledGlsl(
	ShaderAsset* shader,
	std::string& outGLSLCode,
	const TVector<std::string>& includes,
	const TVector<std::string>& defines,
	std::string& outDiagnostic)
{
	SAILOR_PROFILE_FUNCTION();

	std::string generatedSource;

	if (shader->ContainsCommon())
	{
		generatedSource += shader->GetGlslCommonCode() + "\n";
	}

	for (const auto& define : defines)
	{
		generatedSource += "#define " + define + "\n";
	}

	if (!ShaderYamlIncludeResolver::Append(
			includes,
			[](const std::string& include, std::string& outContents)
			{
				if (AssetRegistry* assetRegistry = App::GetSubmodule<AssetRegistry>())
				{
					return assetRegistry->ReadContentText(include, outContents);
				}
				return false;
			},
			generatedSource,
			outDiagnostic))
	{
		outGLSLCode.clear();
		return false;
	}

	if (shader->ContainsVertex() && defines.Contains("VERTEX"))
	{
		generatedSource += "\n#ifdef VERTEX\n" + shader->GetGlslVertexCode() + "\n#endif\n";
	}

	if (shader->ContainsFragment() && defines.Contains("FRAGMENT"))
	{
		generatedSource += "\n#ifdef FRAGMENT\n" + shader->GetGlslFragmentCode() + "\n#endif\n";
	}

	if (shader->ContainsCompute())
	{
		generatedSource += "\n#ifdef COMPUTE\n" + shader->GetGlslComputeCode() + "\n#endif\n";
	}

	outGLSLCode = std::move(generatedSource);
	outDiagnostic.clear();
	return true;
}

bool ShaderCompiler::ForceCompilePermutation(ShaderAssetInfoPtr assetInfo, uint32_t permutation)
{
	SAILOR_PROFILE_FUNCTION();

	auto pShader = LoadShaderAsset(assetInfo).Lock();
	if (!pShader)
	{
		SAILOR_LOG_ERROR(
			"Cannot compile shader because its YAML source could not be loaded: %s",
			assetInfo != nullptr ? assetInfo->GetAssetFilepath().c_str() : "<null asset info>");
		return false;
	}

	ShaderSourceState expectedSourceState;
	std::string sourceDiagnostic;
	if (!m_shaderCache.CaptureSourceState(
			assetInfo->GetFileId(),
			expectedSourceState,
			sourceDiagnostic))
	{
		SAILOR_LOG_ERROR(
			"Cannot capture shader dependencies for %s: %s",
			assetInfo->GetAssetFilepath().c_str(),
			sourceDiagnostic.c_str());
		return false;
	}

	const auto defines = GetDefines(pShader->GetSupportedDefines(), permutation);

	std::string vertexGlsl;
	std::string fragmentGlsl;
	std::string computeGlsl;

	TVector<std::string> vertexDefines = defines;
	TVector<std::string> fragmentDefines = defines;
	TVector<std::string> computeDefines = defines;
	vertexDefines.Add("VERTEX");
	fragmentDefines.Add("FRAGMENT");
	computeDefines.Add("COMPUTE");
#if defined(__APPLE__)
	vertexDefines.Add("SAILOR_TEXTURE_REMAP");
	fragmentDefines.Add("SAILOR_TEXTURE_REMAP");
#endif

	if (pShader->ContainsVertex())
	{
		if (!GeneratePrecompiledGlsl(
				pShader.GetRawPtr(),
				vertexGlsl,
				pShader->GetIncludes(),
				vertexDefines,
				sourceDiagnostic))
		{
			SAILOR_LOG_ERROR(
				"Cannot generate vertex GLSL for %s: %s",
				assetInfo->GetAssetFilepath().c_str(),
				sourceDiagnostic.c_str());
			return false;
		}
	}

	if (pShader->ContainsFragment())
	{
		if (!GeneratePrecompiledGlsl(
				pShader.GetRawPtr(),
				fragmentGlsl,
				pShader->GetIncludes(),
				fragmentDefines,
				sourceDiagnostic))
		{
			SAILOR_LOG_ERROR(
				"Cannot generate fragment GLSL for %s: %s",
				assetInfo->GetAssetFilepath().c_str(),
				sourceDiagnostic.c_str());
			return false;
		}
	}

	if (pShader->ContainsCompute())
	{
		if (!GeneratePrecompiledGlsl(
				pShader.GetRawPtr(),
				computeGlsl,
				pShader->GetIncludes(),
				computeDefines,
				sourceDiagnostic))
		{
			SAILOR_LOG_ERROR(
				"Cannot generate compute GLSL for %s: %s",
				assetInfo->GetAssetFilepath().c_str(),
				sourceDiagnostic.c_str());
			return false;
		}
	}

	const bool bPrecompiledCached = m_shaderCache.CachePrecompiledGlsl(
		assetInfo->GetFileId(),
		permutation,
		vertexGlsl,
		fragmentGlsl,
		computeGlsl);
	if (!bPrecompiledCached)
	{
		SAILOR_LOG_ERROR(
			"Failed to cache precompiled GLSL for shader %s permutation %u: %s",
			assetInfo->GetAssetFilepath().c_str(),
			permutation,
			m_shaderCache.GetLastSaveDiagnostic().c_str());
	}

	RHI::ShaderByteCode spirvVertexByteCode;
	RHI::ShaderByteCode spirvFragmentByteCode;
	RHI::ShaderByteCode spirvComputeByteCode;

	const std::string filename = assetInfo->GetAssetFilepath();

	const bool bResultCompileVertexShader = pShader->ContainsVertex() && CompileGlslToSpirv(filename, vertexGlsl, RHI::EShaderStage::Vertex, spirvVertexByteCode, false);
	const bool bResultCompileFragmentShader = pShader->ContainsFragment() && CompileGlslToSpirv(filename, fragmentGlsl, RHI::EShaderStage::Fragment, spirvFragmentByteCode, false);
	const bool bResultCompileComputeShader = pShader->ContainsCompute() && CompileGlslToSpirv(filename, computeGlsl, RHI::EShaderStage::Compute, spirvComputeByteCode, false);

	const bool bCompiledRegular =
		(bResultCompileVertexShader && bResultCompileFragmentShader) || bResultCompileComputeShader;

	RHI::ShaderByteCode spirvVertexByteCodeDebug;
	RHI::ShaderByteCode spirvFragmentByteCodeDebug;
	RHI::ShaderByteCode spirvComputeByteCodeDebug;

	const bool bResultCompileVertexShaderDebug = pShader->ContainsVertex() && CompileGlslToSpirv(filename, vertexGlsl, RHI::EShaderStage::Vertex, spirvVertexByteCodeDebug, true);
	const bool bResultCompileFragmentShaderDebug = pShader->ContainsFragment() && CompileGlslToSpirv(filename, fragmentGlsl, RHI::EShaderStage::Fragment, spirvFragmentByteCodeDebug, true);
	const bool bResultCompileComputeShaderDebug = pShader->ContainsCompute() && CompileGlslToSpirv(filename, computeGlsl, RHI::EShaderStage::Compute, spirvComputeByteCodeDebug, true);

	const bool bCompiledDebug =
		(bResultCompileVertexShaderDebug && bResultCompileFragmentShaderDebug) || bResultCompileComputeShaderDebug;
	if (bCompiledRegular && !bCompiledDebug)
	{
		SAILOR_LOG_ERROR(
			"Required debug SPIR-V compilation failed for shader %s permutation %u",
			assetInfo->GetAssetFilepath().c_str(),
			permutation);
	}
	const bool bCachedComplete = bCompiledRegular && bCompiledDebug && m_shaderCache.CacheSpirvForSourceFingerprint_ThreadSafe(
		assetInfo->GetFileId(),
		permutation,
		spirvVertexByteCode,
		spirvFragmentByteCode,
		spirvComputeByteCode,
		spirvVertexByteCodeDebug,
		spirvFragmentByteCodeDebug,
		spirvComputeByteCodeDebug,
		expectedSourceState.m_fingerprint);
	if (bCompiledRegular && bCompiledDebug && !bCachedComplete)
	{
		SAILOR_LOG_ERROR(
			"Failed to publish complete SPIR-V generation for shader %s permutation %u: %s",
			assetInfo->GetAssetFilepath().c_str(),
			permutation,
			m_shaderCache.GetLastSaveDiagnostic().c_str());
	}

	return bCompiledRegular && bCompiledDebug && bCachedComplete;
}

void ShaderCompiler::RecordCompileResult(
	std::atomic_bool& aggregate,
	bool bSucceeded) noexcept
{
	if (!bSucceeded)
	{
		aggregate.store(false, std::memory_order_release);
	}
}

bool ShaderCompiler::SaveShaderCacheAndCombineResult(
	ShaderCache& cache,
	bool bCompiledSuccessfully)
{
	cache.SaveCache();
	return bCompiledSuccessfully && !cache.IsDirty();
}

bool ShaderCompiler::ShouldRetryDirtyShaderCache(
	size_t numPermutationsToCompile,
	bool bCacheDirty) noexcept
{
	return numPermutationsToCompile == 0 && bCacheDirty;
}

TVector<FileId> ShaderCompiler::MergeShaderDependencyCandidates(
	const TVector<FileId>& parsedShaderIds,
	const TVector<FileId>& loadedShaderIds)
{
	TVector<FileId> result = parsedShaderIds;
	result.Reserve(parsedShaderIds.Num() + loadedShaderIds.Num());
	for (const FileId& loadedShaderId : loadedShaderIds)
	{
		if (!result.Contains(loadedShaderId))
		{
			result.Add(loadedShaderId);
		}
	}
	return result;
}

std::string ShaderCompiler::NormalizeShaderExtension(const std::string& filepath)
{
	std::string extension = Utils::GetFileExtension(filepath);
	std::transform(extension.begin(), extension.end(), extension.begin(), [](unsigned char character)
		{
			return static_cast<char>(std::tolower(character));
		});
	return extension;
}

bool ShaderCompiler::DoesShaderIncludePath(
	const TVector<std::string>& includes,
	const std::string& relativePath)
{
	auto normalize = [](const std::string& path)
	{
		std::string result = std::filesystem::path(path).lexically_normal().generic_string();
#if defined(_WIN32)
		std::transform(result.begin(), result.end(), result.begin(), [](unsigned char character)
			{
				return static_cast<char>(std::tolower(character));
			});
#endif
		return result;
	};

	const std::string normalizedRelativePath = normalize(relativePath);
	return includes.ContainsIf([&](const std::string& include)
		{
			return normalize(include) == normalizedRelativePath;
		});
}

void ShaderCompiler::RemoveFinishedPromiseEntries(
	TVector<TPair<uint32_t, Tasks::TaskPtr<ShaderSetPtr>>>& entries)
{
	RemoveMatchingEntries(entries, [](const Tasks::TaskPtr<ShaderSetPtr>& promise)
		{
			return promise && promise->IsFinished();
		});
}

Tasks::TaskPtr<bool> ShaderCompiler::CompileAllPermutations(const FileId& uid)
{
	return CompileAllPermutations(dynamic_cast<ShaderAssetInfoPtr>(App::GetSubmodule<AssetRegistry>()->GetAssetInfoPtr(uid)));
}

TWeakPtr<ShaderAsset> ShaderCompiler::LoadShaderAsset(const FileId& uid)
{
	return LoadShaderAsset(dynamic_cast<ShaderAssetInfoPtr>(App::GetSubmodule<AssetRegistry>()->GetAssetInfoPtr(uid)));
}

Tasks::TaskPtr<bool> ShaderCompiler::CompileAllPermutations(ShaderAssetInfoPtr assetInfo)
{
	SAILOR_PROFILE_FUNCTION();
	if (TWeakPtr<ShaderAsset> pWeakShader = LoadShaderAsset(assetInfo))
	{
		FileId assetFileId = assetInfo->GetFileId();

		TSharedPtr<ShaderAsset> pShader = pWeakShader.Lock();

		if ((!pShader->ContainsFragment() || !pShader->ContainsVertex()) && !pShader->ContainsCompute())
		{
			SAILOR_LOG("Skip shader compilation (missing fragment/vertex module): %s", assetInfo->GetAssetFilepath().c_str());

			return Tasks::TaskPtr<bool>::Make(false);
		}

		const uint32_t NumPermutations = (uint32_t)std::pow(2, pShader->GetSupportedDefines().Num());

		TVector<uint32_t> permutationsToCompile;

		for (uint32_t permutation = 0; permutation < NumPermutations; permutation++)
		{
			if (m_shaderCache.IsExpired(assetFileId, permutation))
			{
				permutationsToCompile.Add(permutation);
			}
		}

		auto scheduler = App::GetSubmodule<Tasks::Scheduler>();
		if (permutationsToCompile.IsEmpty())
		{
			if (ShouldRetryDirtyShaderCache(permutationsToCompile.Num(), m_shaderCache.IsDirty()))
			{
				Tasks::TaskPtr<bool> retrySaveJob = Tasks::CreateTaskWithResult<bool>(
					"Retry Save Shader Cache",
					[this]()
					{
						return SaveShaderCacheAndCombineResult(m_shaderCache, true);
					});
				scheduler->Run(retrySaveJob);
				return retrySaveJob;
			}
			return Tasks::TaskPtr<bool>::Make(false);
		}

		SAILOR_LOG("Compiling shader: %s Num permutations: %zd", assetInfo->GetAssetFilepath().c_str(), permutationsToCompile.Num());

		auto compileSucceeded = TSharedPtr<std::atomic_bool>::Make(true);
		Tasks::TaskPtr<bool> saveCacheJob = Tasks::CreateTaskWithResult<bool>("Save Shader Cache", [=, this]()
			{
				const bool bCompiled = compileSucceeded->load(std::memory_order_acquire);
				SAILOR_LOG(
					bCompiled ? "Shader compiled %s" : "Shader compilation failed %s",
					assetInfo->GetAssetFilepath().c_str());
				const bool bResult = SaveShaderCacheAndCombineResult(m_shaderCache, bCompiled);

				//Unload shader asset text
				m_shaderAssetsCache.Remove(assetInfo->GetFileId());

				return bResult;
			});

		for (uint32_t i = 0; i < permutationsToCompile.Num(); i++)
		{
			Tasks::TaskPtr<bool> job = Tasks::CreateTaskWithResult<bool>("Compile shader", [i, assetInfo, permutationsToCompile, compileSucceeded]()
				{
					SAILOR_LOG("Start compiling shader %d", permutationsToCompile[i]);
					const bool bSucceeded = App::GetSubmodule<ShaderCompiler>()->ForceCompilePermutation(
						assetInfo,
						permutationsToCompile[i]);
					ShaderCompiler::RecordCompileResult(*compileSucceeded, bSucceeded);
					return bSucceeded;
				});

			saveCacheJob->Join(job);
			scheduler->Run(job);
		}
		scheduler->Run(saveCacheJob);

		return saveCacheJob;
	}
	else
	{
		SAILOR_LOG("Cannot find shader asset");
	}

	return Tasks::TaskPtr<bool>::Make(false);
}

TWeakPtr<ShaderAsset> ShaderCompiler::LoadShaderAsset(ShaderAssetInfoPtr shaderAssetInfo)
{
	SAILOR_PROFILE_FUNCTION();

	if (shaderAssetInfo)
	{
		FileId uid = shaderAssetInfo->GetFileId();

		auto& shaderAsset = m_shaderAssetsCache.At_Lock(uid);
		TConcurrentMapEntryUnlockGuard shaderAssetUnlockGuard(m_shaderAssetsCache, uid);
		if (shaderAsset)
		{
			return shaderAsset;
		}

		const std::string& filepath = shaderAssetInfo->GetAssetFilepath();

		std::string shaderText;
		if (!AssetRegistry::ReadAllTextFile(filepath, shaderText))
		{
			SAILOR_LOG_ERROR("Cannot read shader YAML '%s'.", filepath.c_str());
			return TWeakPtr<ShaderAsset>();
		}

		std::string yamlDiagnostic;
		NormalizeShaderTabs("shader", shaderText, yamlDiagnostic);
		if (!yamlDiagnostic.empty())
		{
			SAILOR_LOG_ERROR("Cannot parse shader YAML '%s': %s", filepath.c_str(), yamlDiagnostic.c_str());
			return TWeakPtr<ShaderAsset>();
		}

		YAML::Node yamlNode;
		if (!External::TryLoadYaml(shaderText, yamlNode, yamlDiagnostic))
		{
			SAILOR_LOG_ERROR("Cannot parse shader YAML '%s': %s", filepath.c_str(), yamlDiagnostic.c_str());
			return TWeakPtr<ShaderAsset>();
		}

		ShaderAsset* shader = new ShaderAsset();
		if (!External::GuardYamlExceptions(
				[shader, &yamlNode]()
				{
					shader->Deserialize(yamlNode);
				},
				yamlDiagnostic))
		{
			SAILOR_LOG_ERROR("Cannot deserialize shader YAML '%s': %s", filepath.c_str(), yamlDiagnostic.c_str());
			delete shader;
			return TWeakPtr<ShaderAsset>();
		}
		shaderAsset = TSharedPtr<ShaderAsset>(shader);

		return shaderAsset;
	}

	SAILOR_LOG("Cannot find shader asset info!");
	return TWeakPtr<ShaderAsset>();
}

bool ShaderCompiler::RecoverMissingShaderCacheStorage()
{
	if (!m_shaderCache.RecoverMissingStorage())
	{
		return false;
	}

	m_loadedShaders.LockAll();
	const TVector<FileId> loadedShaderIds = m_loadedShaders.GetKeys();
	m_loadedShaders.UnlockAll();

	bool bReloadedAny = false;
	bool bAllReloaded = true;
	for (const FileId& shaderId : loadedShaderIds)
	{
		auto& loadedShaders = m_loadedShaders.At_Lock(shaderId);
		for (auto& loadedShader : loadedShaders)
		{
			if (UpdateRHIResource(loadedShader.m_second, loadedShader.m_first))
			{
				loadedShader.m_second->TraceHotReload(nullptr);
				bReloadedAny = true;
			}
			else
			{
				bAllReloaded = false;
			}
		}
		m_loadedShaders.Unlock(shaderId);
	}

	if (bReloadedAny || !bAllReloaded)
	{
		SaveShaderCacheAndCombineResult(m_shaderCache, bAllReloaded);
	}
	SAILOR_LOG(
		"Recovered missing shader cache storage; reloaded=%s loadedShaderAssets=%zd.",
		bAllReloaded ? "true" : "false",
		loadedShaderIds.Num());
	return true;
}

void ShaderCompiler::OnUpdateAssetInfo(AssetInfoPtr assetInfo, bool bWasExpired)
{
	SAILOR_PROFILE_FUNCTION();
	SAILOR_PROFILE_TEXT(assetInfo->GetAssetFilepath().c_str());

	if (bWasExpired)
	{
		const std::string extension = NormalizeShaderExtension(assetInfo->GetAssetFilepath());

		ReplaceTabsWithSpaces(assetInfo);

		if (extension == "shader")
		{
			AssetRegistry* assetRegistry = App::GetSubmodule<AssetRegistry>();
			const AssetRegistry::AssetProcessingToken processingToken =
				assetRegistry != nullptr
				? assetRegistry->BeginAssetProcessing(assetInfo)
				: AssetRegistry::AssetProcessingToken{};
			if (!processingToken)
			{
				return;
			}
			TrackAssetProcessing(
				processingToken,
				ReloadShader(dynamic_cast<ShaderAssetInfoPtr>(assetInfo)));
		}
		else if (extension == "glsl")
		{
			AssetRegistry* assetRegistry = App::GetSubmodule<AssetRegistry>();
			const AssetRegistry::AssetProcessingToken processingToken =
				assetRegistry != nullptr
				? assetRegistry->BeginAssetProcessing(assetInfo)
				: AssetRegistry::AssetProcessingToken{};
			if (!processingToken)
			{
				return;
			}
			TrackAssetProcessing(
				processingToken,
				ReloadShadersDependingOn(assetInfo));
		}

		if (assetInfo->IsWritable())
		{
			assetInfo->SaveMetaFile();
		}
	}
}

Tasks::TaskPtr<bool> ShaderCompiler::ReloadShader(ShaderAssetInfoPtr assetInfo)
{
	if (assetInfo == nullptr)
	{
		return Tasks::TaskPtr<bool>::Make(false);
	}

	const FileId fileId = assetInfo->GetFileId();
	SAILOR_LOG("Updated shader info: %s", assetInfo->GetAssetFilepath().c_str());

	m_shaderAssetsCache.Remove(fileId);
	m_shaderCache.Invalidate(fileId);

	if (!bShouldAutoCompileAllPermutations)
	{
		return Tasks::TaskPtr<bool>::Make(
			ReloadLoadedShaderResources(assetInfo, true));
	}

	Tasks::TaskPtr<bool> compileTask = CompileAllPermutations(assetInfo);
	if (!compileTask)
	{
		return Tasks::TaskPtr<bool>::Make(false);
	}
	if (compileTask->IsFinished())
	{
		return Tasks::TaskPtr<bool>::Make(
			compileTask->GetResult() && ReloadLoadedShaderResources(assetInfo, false));
	}

	Tasks::TaskPtr<bool> updateRhiTask = Tasks::CreateTaskWithResult<bool>(
		"Update Shader RHI",
		[this, fileId, compileTask]()
		{
			const bool bCompiled = compileTask->GetResult();
			if (!bCompiled)
			{
				return false;
			}

			AssetRegistry* currentRegistry = App::GetSubmodule<AssetRegistry>();
			if (currentRegistry == nullptr)
			{
				return false;
			}

			ShaderAssetInfoPtr currentAssetInfo =
				currentRegistry->GetAssetInfoPtr<ShaderAssetInfoPtr>(fileId);
			return ReloadLoadedShaderResources(currentAssetInfo, false);
		});
	updateRhiTask->Join(compileTask);
	updateRhiTask->Run();
	return updateRhiTask;
}

Tasks::TaskPtr<bool> ShaderCompiler::ReloadShadersDependingOn(AssetInfoPtr includeAssetInfo)
{
	if (includeAssetInfo == nullptr)
	{
		return Tasks::TaskPtr<bool>::Make(false);
	}
	return ReloadShadersDependingOn(includeAssetInfo->GetRelativeAssetFilepath());
}

Tasks::TaskPtr<bool> ShaderCompiler::ReloadShadersDependingOn(
	const std::string& includeVirtualPath)
{
	AssetRegistry* assetRegistry = App::GetSubmodule<AssetRegistry>();
	if (assetRegistry == nullptr)
	{
		return Tasks::TaskPtr<bool>::Make(false);
	}

	TVector<FileId> dependencyCandidates;
	assetRegistry->GetAllAssetInfos<ShaderAssetInfo>(dependencyCandidates);
	TVector<Tasks::TaskPtr<bool>> reloadTasks;
	for (const FileId& shaderId : dependencyCandidates)
	{
		ShaderAssetInfoPtr shaderAssetInfo =
			assetRegistry->GetAssetInfoPtr<ShaderAssetInfoPtr>(shaderId);
		if (shaderAssetInfo == nullptr ||
			NormalizeShaderExtension(shaderAssetInfo->GetAssetFilepath()) != "shader")
		{
			continue;
		}

		TSharedPtr<ShaderAsset> shader = LoadShaderAsset(shaderAssetInfo).Lock();
		if (!shader || !DoesShaderIncludePath(
				shader->GetIncludes(),
				includeVirtualPath))
		{
			continue;
		}

		reloadTasks.Add(ReloadShader(shaderAssetInfo));
	}
	return AggregateShaderReloadTasks(reloadTasks);
}

Tasks::TaskPtr<bool> ShaderCompiler::OnEffectiveContentChanged(
	const std::string& virtualPath)
{
	if (NormalizeShaderExtension(virtualPath) == "glsl")
	{
		return ReloadShadersDependingOn(virtualPath);
	}
	return Tasks::TaskPtr<bool>::Make(true);
}

bool ShaderCompiler::ReloadLoadedShaderResources(
	ShaderAssetInfoPtr assetInfo,
	bool bCompileBeforeRhiUpdate)
{
	if (assetInfo == nullptr)
	{
		return false;
	}

	const FileId fileId = assetInfo->GetFileId();
	auto& loadedShaders = m_loadedShaders.At_Lock(fileId);
	if (loadedShaders.IsEmpty())
	{
		m_loadedShaders.Unlock(fileId);
		return true;
	}

	if (bCompileBeforeRhiUpdate && !LoadShaderAsset(assetInfo).Lock())
	{
		m_loadedShaders.Unlock(fileId);
		return false;
	}

	if (bCompileBeforeRhiUpdate)
	{
		bool bAllCompiled = true;
		for (const auto& loadedShader : loadedShaders)
		{
			if (m_shaderCache.IsExpired(fileId, loadedShader.m_first) &&
				!ForceCompilePermutation(assetInfo, loadedShader.m_first))
			{
				bAllCompiled = false;
			}
		}
		if (!bAllCompiled || !SaveShaderCacheAndCombineResult(m_shaderCache, true))
		{
			m_loadedShaders.Unlock(fileId);
			return false;
		}
	}

	bool bAllReloaded = true;
	for (auto& loadedShader : loadedShaders)
	{
		SAILOR_LOG(
			"Update shader RHI resource: %s permutation: %u",
			assetInfo->GetAssetFilepath().c_str(),
			static_cast<uint32_t>(loadedShader.m_first));

		if (UpdateRHIResource(loadedShader.m_second, loadedShader.m_first))
		{
			loadedShader.m_second->TraceHotReload(nullptr);
		}
		else
		{
			bAllReloaded = false;
		}
	}
	m_loadedShaders.Unlock(fileId);
	return bAllReloaded;
}

Tasks::TaskPtr<bool> ShaderCompiler::AggregateShaderReloadTasks(
	const TVector<Tasks::TaskPtr<bool>>& reloadTasks)
{
	bool bAllFinished = true;
	bool bImmediateResult = true;
	for (const Tasks::TaskPtr<bool>& reloadTask : reloadTasks)
	{
		if (!reloadTask)
		{
			bImmediateResult = false;
			continue;
		}
		if (!reloadTask->IsFinished())
		{
			bAllFinished = false;
			continue;
		}
		bImmediateResult &= reloadTask->GetResult();
	}
	if (bAllFinished)
	{
		return Tasks::TaskPtr<bool>::Make(bImmediateResult);
	}

	Tasks::TaskPtr<bool> aggregateTask = Tasks::CreateTaskWithResult<bool>(
		"Aggregate Shader Reload",
		[reloadTasks]()
		{
			bool bResult = true;
			for (const Tasks::TaskPtr<bool>& reloadTask : reloadTasks)
			{
				bResult &= reloadTask && reloadTask->GetResult();
			}
			return bResult;
		});
	for (const Tasks::TaskPtr<bool>& reloadTask : reloadTasks)
	{
		aggregateTask->Join(reloadTask);
	}
	aggregateTask->Run();
	return aggregateTask;
}

void ShaderCompiler::ReplaceTabsWithSpaces(AssetInfoPtr assetInfo) const
{
	if (!assetInfo->IsWritable())
	{
		return;
	}

	const std::string& filepath = assetInfo->GetAssetFilepath();
	const std::string extension = NormalizeShaderExtension(filepath);
	if (extension != "shader")
	{
		return;
	}

	std::string shaderText;
	std::string readDiagnostic;
	if (!ReadShaderSourceBinary(filepath, shaderText, readDiagnostic))
	{
		SAILOR_LOG_ERROR(
			"Cannot read shader YAML '%s': %s",
			filepath.c_str(),
			readDiagnostic.c_str());
		return;
	}
	const std::string originalShaderText = shaderText;

	std::string yamlDiagnostic;
	if (!NormalizeShaderTabs(extension, shaderText, yamlDiagnostic))
	{
		if (!yamlDiagnostic.empty())
		{
			SAILOR_LOG_ERROR("Cannot parse shader YAML '%s': %s", filepath.c_str(), yamlDiagnostic.c_str());
		}
		return;
	}

	std::string writeDiagnostic;
	if (!RewriteShaderSourceInPlace(
			filepath,
			originalShaderText,
			shaderText,
			writeDiagnostic))
	{
		SAILOR_LOG_ERROR(
			"Cannot safely rewrite shader YAML '%s': %s",
			filepath.c_str(),
			writeDiagnostic.c_str());
	}
}

bool ShaderCompiler::ReadShaderSourceBinary(
	const std::string& filepath,
	std::string& outSource,
	std::string& outDiagnostic)
{
	outSource.clear();
	outDiagnostic.clear();
	std::ifstream shaderFile(filepath, std::ios::in | std::ios::binary);
	if (!shaderFile.is_open())
	{
		outDiagnostic = "Cannot open the shader source for reading.";
		return false;
	}

	outSource.assign(
		std::istreambuf_iterator<char>{ shaderFile },
		std::istreambuf_iterator<char>{});
	if (shaderFile.bad())
	{
		outSource.clear();
		outDiagnostic = "Cannot read the complete shader source.";
		return false;
	}

	return true;
}

bool ShaderCompiler::RewriteShaderSourceInPlace(
	const std::string& filepath,
	const std::string& expectedSource,
	const std::string& replacement,
	std::string& outDiagnostic)
{
	outDiagnostic.clear();
	if (replacement.size() < expectedSource.size())
	{
		outDiagnostic = "The normalized shader source must not be smaller than the original source.";
		return false;
	}

	if (replacement.size() > static_cast<size_t>((std::numeric_limits<std::streamsize>::max)()))
	{
		outDiagnostic = "The normalized shader source is too large to write.";
		return false;
	}

	std::fstream shaderFile(filepath, std::ios::in | std::ios::out | std::ios::binary);
	if (!shaderFile.is_open())
	{
		outDiagnostic = "Cannot open the shader source for an in-place update.";
		return false;
	}

	const std::string currentSource{
		std::istreambuf_iterator<char>{ shaderFile },
		std::istreambuf_iterator<char>{} };
	if (shaderFile.bad())
	{
		outDiagnostic = "Cannot verify the shader source before updating it.";
		return false;
	}

	if (currentSource != expectedSource)
	{
		outDiagnostic = "The shader source changed while it was being normalized.";
		return false;
	}

	shaderFile.clear();
	shaderFile.seekp(0, std::ios::beg);
	if (!shaderFile.good())
	{
		outDiagnostic = "Cannot seek to the beginning of the shader source.";
		return false;
	}

	shaderFile.write(
		replacement.data(),
		static_cast<std::streamsize>(replacement.size()));
	shaderFile.flush();
	if (!shaderFile.good())
	{
		outDiagnostic = "Cannot write the normalized shader source.";
		return false;
	}
	shaderFile.close();
	if (shaderFile.fail())
	{
		outDiagnostic = "Cannot close the normalized shader source.";
		return false;
	}

	return true;
}

bool ShaderCompiler::NormalizeShaderTabs(
	const std::string& extension,
	std::string& shaderText,
	std::string& outDiagnostic)
{
	outDiagnostic.clear();
	if (extension != "shader")
	{
		return false;
	}

	YAML::Node yamlNode;
	if (External::TryLoadYaml(shaderText, yamlNode, outDiagnostic))
	{
		return false;
	}

	if (shaderText.find('\t') == std::string::npos)
	{
		return false;
	}

	std::string normalizedShaderText = shaderText;
	static const std::string tab = "\t";
	static const std::string space = "    ";
	Utils::ReplaceAll(normalizedShaderText, tab, space);

	std::string normalizedDiagnostic;
	if (!External::TryLoadYaml(normalizedShaderText, yamlNode, normalizedDiagnostic))
	{
		outDiagnostic = std::move(normalizedDiagnostic);
		return false;
	}

	shaderText = std::move(normalizedShaderText);
	outDiagnostic.clear();
	return true;
}

void ShaderCompiler::OnImportAsset(AssetInfoPtr assetInfo)
{
	ReplaceTabsWithSpaces(assetInfo);
	AssetRegistry* assetRegistry = App::GetSubmodule<AssetRegistry>();
	const AssetRegistry::AssetProcessingToken processingToken =
		assetRegistry != nullptr
		? assetRegistry->BeginAssetProcessing(assetInfo)
		: AssetRegistry::AssetProcessingToken{};
	if (!processingToken)
	{
		return;
	}
	const std::string extension = NormalizeShaderExtension(assetInfo->GetAssetFilepath());
	Tasks::TaskPtr<bool> processingTask;
	if (extension == "shader")
	{
		processingTask = ReloadShader(dynamic_cast<ShaderAssetInfoPtr>(assetInfo));
	}
	else if (extension == "glsl")
	{
		processingTask = ReloadShadersDependingOn(assetInfo);
	}
	TrackAssetProcessing(processingToken, processingTask);
}

bool ShaderCompiler::CompileGlslToSpirv(const std::string& filename, const std::string& source, RHI::EShaderStage shaderStage, RHI::ShaderByteCode& outByteCode, bool bIsDebug)
{
	SAILOR_PROFILE_FUNCTION();

	shaderc::Compiler compiler;
	shaderc::CompileOptions options;

	options.SetSourceLanguage(shaderc_source_language_glsl);

	if (bIsDebug)
	{
		options.SetGenerateDebugInfo();
		options.SetOptimizationLevel(shaderc_optimization_level_zero);
	}
	else
	{
		options.SetOptimizationLevel(shaderc_optimization_level_performance);
	}

	shaderc_shader_kind kind = shaderc_glsl_anyhit_shader;
	switch (shaderStage)
	{
	case RHI::EShaderStage::Fragment:
		kind = shaderc_glsl_fragment_shader;
		break;
	case RHI::EShaderStage::Vertex:
		kind = shaderc_glsl_vertex_shader;
		break;
	case RHI::EShaderStage::Compute:
		kind = shaderc_glsl_compute_shader;
		break;
	default:
		check(false);
		break;
	}

	// Includes are an explicit YAML dependency list expanded by
	// GeneratePrecompiledGlsl. Native/nested GLSL #include directives are not
	// enabled until they have a separate path and dependency contract.

	shaderc::SpvCompilationResult module = compiler.CompileGlslToSpv(source, kind, filename.c_str(), "main", options);

	if (module.GetCompilationStatus() != shaderc_compilation_status::shaderc_compilation_status_success)
	{
		//const size_t numErrors = module.GetNumErrors();
		//const size_t numWarnings = module.GetNumWarnings();
		const std::string fullError = module.GetErrorMessage();

		uint32_t start = 0;
		bool bFound = false;
		uint32_t lineNum = 0;

		SAILOR_LOG("Failed to compile shader");

		uint32_t errorNum = 1;
		auto errors = Utils::SplitStringByLines(fullError);
		for (const auto& error : errors)
		{
			SAILOR_LOG_ERROR("Error %d: %s", errorNum++, error.c_str());

			for (uint32_t i = 0; i < error.size(); i++)
			{
				if (error[i] == ':')
				{
					if (!bFound)
					{
						start = i;
						bFound = true;
					}
					else
					{
						std::string str = error.substr(start + 1, i - start - 2);
						lineNum = static_cast<uint32_t>(std::stoul(str) - 1);
					}
				}
			}

			auto lines = Utils::SplitStringByLines(source);

			if (lineNum < lines.Num())
			{
				SAILOR_LOG("%s\n", lines[lineNum].c_str());
			}
		}

		return false;
	}

	outByteCode = TVector(module.cbegin(), module.cend() - module.cbegin());

	return true;
}

uint32_t ShaderCompiler::GetPermutation(const TVector<std::string>& defines, const TVector<std::string>& actualDefines)
{
	SAILOR_PROFILE_FUNCTION();

	if (actualDefines.Num() == 0)
	{
		return 0;
	}

	TSet<std::string> requested;

	for (int32_t i = 0; i < actualDefines.Num(); i++)
	{
		requested.Insert(actualDefines[i]);
	}

	uint32_t res = 0;
	for (int32_t i = 0; i < defines.Num(); i++)
	{
		if (requested.Contains(defines[i]))
		{
			res += 1 << i;
		}
	}
	return res;
}

TVector<std::string> ShaderCompiler::GetDefines(const TVector<std::string>& defines, uint32_t permutation)
{
	SAILOR_PROFILE_FUNCTION();

	TVector<std::string> res;

	for (int32_t define = 0; define < defines.Num(); define++)
	{
		if ((permutation >> define) & 1)
		{
			res.Add(defines[define]);
		}
	}

	return res;
}

bool ShaderCompiler::GetSpirvCode(const FileId& assetFileId, const TVector<std::string>& defines, RHI::ShaderByteCode& outVertexByteCode, RHI::ShaderByteCode& outFragmentByteCode, RHI::ShaderByteCode& outComputeByteCode, bool bIsDebug)
{
	if (auto pShader = LoadShaderAsset(assetFileId).Lock())
	{
		return GetSpirvCode(assetFileId, GetPermutation(pShader->GetSupportedDefines(), defines), outVertexByteCode, outFragmentByteCode, outComputeByteCode, bIsDebug);
	}
	return false;
}

bool ShaderCompiler::GetSpirvCode(const FileId& assetFileId, uint32_t permutation, RHI::ShaderByteCode& outVertexByteCode, RHI::ShaderByteCode& outFragmentByteCode, RHI::ShaderByteCode& outComputeByteCode, bool bIsDebug)
{
	SAILOR_PROFILE_FUNCTION();

	if (ShaderAssetInfoPtr assetInfo = dynamic_cast<ShaderAssetInfoPtr>(App::GetSubmodule<AssetRegistry>()->GetAssetInfoPtr(assetFileId)))
	{
		if (auto pShader = LoadShaderAsset(assetInfo).Lock())
		{
			bool bCompiledSuccesfully = true;
			if (m_shaderCache.IsExpired(assetFileId, permutation))
			{
				bCompiledSuccesfully = ForceCompilePermutation(assetInfo, permutation);
			}

			return m_shaderCache.GetSpirvCode(assetFileId, permutation, outVertexByteCode, outFragmentByteCode, outComputeByteCode, bIsDebug) && bCompiledSuccesfully;
		}
	}

	return false;
}

Tasks::TaskPtr<ShaderSetPtr> ShaderCompiler::LoadShader(FileId uid, ShaderSetPtr& outShader, const TVector<string>& defines)
{
	SAILOR_PROFILE_FUNCTION();

	outShader = nullptr;
	auto shaderAsset = LoadShaderAsset(uid).TryLock();
	if (!shaderAsset)
	{
		SAILOR_LOG("Cannot find shader with uid: %s", uid.ToString().c_str());
		return Tasks::TaskPtr<ShaderSetPtr>();
	}

	const uint32_t permutation = GetPermutation(shaderAsset->GetSupportedDefines(), defines);
	ShaderAssetInfoPtr assetInfo =
		App::GetSubmodule<AssetRegistry>()->GetAssetInfoPtr<ShaderAssetInfoPtr>(uid);
	if (!assetInfo)
	{
		SAILOR_LOG("Cannot find shader with uid: %s", uid.ToString().c_str());
		return Tasks::TaskPtr<ShaderSetPtr>();
	}
	SAILOR_PROFILE_TEXT(assetInfo->GetAssetFilepath().c_str());

	Tasks::TaskPtr<ShaderSetPtr> newPromise;
	{
		auto& promises = m_promises.At_Lock(uid);
		TConcurrentMapEntryUnlockGuard promisesUnlockGuard(m_promises, uid);
		auto& shaders = m_loadedShaders.At_Lock(uid);
		TConcurrentMapEntryUnlockGuard shadersUnlockGuard(m_loadedShaders, uid);
		const size_t promiseIndex = FindPermutationIndex(promises, permutation);
		const size_t shaderIndex = FindPermutationIndex(shaders, permutation);
		if (shaderIndex != static_cast<size_t>(-1))
		{
			outShader = shaders[shaderIndex].m_second;
			return promiseIndex == static_cast<size_t>(-1)
				? Tasks::TaskPtr<ShaderSetPtr>::Make(outShader)
				: promises[promiseIndex].m_second;
		}
		if (promiseIndex != static_cast<size_t>(-1))
		{
			return promises[promiseIndex].m_second;
		}

		auto pShader = ShaderSetPtr::Make(m_allocator, uid, defines);
		newPromise = Tasks::CreateTaskWithResult<ShaderSetPtr>(
			"Load shader",
			[pShader, this, uid, permutation]() mutable
			{
				if (!UpdateRHIResource(pShader, permutation))
				{
					{
						auto& failedPromises = m_promises.At_Lock(uid);
						TConcurrentMapEntryUnlockGuard promisesUnlockGuard(m_promises, uid);
						auto& failedShaders = m_loadedShaders.At_Lock(uid);
						TConcurrentMapEntryUnlockGuard shadersUnlockGuard(m_loadedShaders, uid);
						EvictFailedShaderLoadEntries(failedPromises, failedShaders, permutation);
					}
					pShader.DestroyObject(m_allocator);
					return ShaderSetPtr{};
				}
				return pShader;
			});

		AddShaderLoadEntries(promises, shaders, permutation, newPromise, pShader);
		outShader = pShader;
	}
	App::GetSubmodule<Tasks::Scheduler>()->Run(newPromise);
	return newPromise;
}

bool ShaderCompiler::LoadShader_Immediate(FileId uid, ShaderSetPtr& outShader, const TVector<string>& defines)
{
	SAILOR_PROFILE_FUNCTION();
	auto task = LoadShader(uid, outShader, defines);

	if (!task)
	{
		return false;
	}

	task->Wait();
	outShader = task->GetResult();
	if (!outShader.IsValid())
	{
		return false;
	}
	return true;
}

bool ShaderCompiler::UpdateRHIResource(ShaderSetPtr pShader, uint32_t permutation)
{
	SAILOR_PROFILE_FUNCTION();

	auto pRaw = pShader.GetRawPtr();
	auto& pRhiDriver = App::GetSubmodule<RHI::Renderer>()->GetDriver();
	AssetInfoPtr assetInfo = App::GetSubmodule<AssetRegistry>()->GetAssetInfoPtr(pShader->GetFileId());
	if (!assetInfo)
	{
		SAILOR_LOG_ERROR(
			"UpdateRHIResource could not resolve asset metadata for shader %s permutation %u",
			pShader->GetFileId().ToString().c_str(),
			permutation);
		return false;
	}
	const std::string assetFilename = assetInfo->GetAssetFilepath();

	RHI::ShaderByteCode debugVertexSpirv;
	RHI::ShaderByteCode debugFragmentSpirv;
	RHI::ShaderByteCode debugComputeFragmentSpirv;
	if (!GetSpirvCode(pShader->GetFileId(), permutation, debugVertexSpirv, debugFragmentSpirv, debugComputeFragmentSpirv, true))
	{
		SAILOR_LOG_ERROR("UpdateRHIResource failed to get DEBUG spirv for shader %s permutation %u", pShader->GetFileId().ToString().c_str(), permutation);
		return false;
	}

	RHI::ShaderByteCode vertexByteCode;
	RHI::ShaderByteCode fragmentByteCode;
	RHI::ShaderByteCode computeByteCode;
	if (!GetSpirvCode(pShader->GetFileId(), permutation, vertexByteCode, fragmentByteCode, computeByteCode, false))
	{
		SAILOR_LOG_ERROR("UpdateRHIResource failed to get RELEASE spirv for shader %s permutation %u", pShader->GetFileId().ToString().c_str(), permutation);
		return false;
	}

	auto createShader = [&](RHI::EShaderStage stage,
		const RHI::ShaderByteCode& byteCode,
		RHI::RHIShaderPtr& outShader,
		const std::string& debugName) -> bool
	{
		if (byteCode.IsEmpty())
		{
			return true;
		}
		outShader = pRhiDriver->CreateShader(stage, byteCode);
		if (!outShader)
		{
			SAILOR_LOG_ERROR(
				"UpdateRHIResource failed to create %s for shader %s permutation %u",
				debugName.c_str(),
				pShader->GetFileId().ToString().c_str(),
				permutation);
			return false;
		}
		pRhiDriver->SetDebugName(outShader, debugName + " " + assetFilename);
		return true;
	};
	RHI::RHIShaderPtr stagedVertexShader;
	RHI::RHIShaderPtr stagedFragmentShader;
	RHI::RHIShaderPtr stagedComputeShader;
	RHI::RHIShaderPtr stagedDebugVertexShader;
	RHI::RHIShaderPtr stagedDebugFragmentShader;
	RHI::RHIShaderPtr stagedDebugComputeShader;

	if (!createShader(
		RHI::EShaderStage::Vertex,
		debugVertexSpirv,
		stagedDebugVertexShader,
		"Debug Vertex") ||
		!createShader(
			RHI::EShaderStage::Fragment,
			debugFragmentSpirv,
			stagedDebugFragmentShader,
			"Debug Fragment") ||
		!createShader(
			RHI::EShaderStage::Compute,
			debugComputeFragmentSpirv,
			stagedDebugComputeShader,
			"Debug Compute") ||
		!createShader(
			RHI::EShaderStage::Vertex,
			vertexByteCode,
			stagedVertexShader,
			"Vertex") ||
		!createShader(
			RHI::EShaderStage::Fragment,
			fragmentByteCode,
			stagedFragmentShader,
			"Fragment") ||
		!createShader(
			RHI::EShaderStage::Compute,
			computeByteCode,
			stagedComputeShader,
			"Compute"))
	{
		return false;
	}

	const bool bRegularReady =
		(stagedVertexShader && stagedFragmentShader) || stagedComputeShader;
	const bool bDebugReady =
		(stagedDebugVertexShader && stagedDebugFragmentShader) || stagedDebugComputeShader;
	if (!bRegularReady || !bDebugReady)
	{
		SAILOR_LOG_ERROR(
			"UpdateRHIResource staged an incomplete regular/debug shader set for shader %s permutation %u",
			pShader->GetFileId().ToString().c_str(),
			permutation);
		return false;
	}

	auto pShaderAsset = LoadShaderAsset(pShader->GetFileId()).Lock();
	if (!pShaderAsset)
	{
		SAILOR_LOG_ERROR(
			"UpdateRHIResource could not reload shader metadata for shader %s permutation %u",
			pShader->GetFileId().ToString().c_str(),
			permutation);
		return false;
	}
	const TVector<RHI::EFormat> stagedColorAttachments = pShaderAsset->GetColorAttachments();
	const RHI::EFormat stagedDepthStencilAttachment = pShaderAsset->GetDepthStencilAttachment();

	pRaw->m_rhiVertexShader = std::move(stagedVertexShader);
	pRaw->m_rhiFragmentShader = std::move(stagedFragmentShader);
	pRaw->m_rhiComputeShader = std::move(stagedComputeShader);
	pRaw->m_rhiVertexShaderDebug = std::move(stagedDebugVertexShader);
	pRaw->m_rhiFragmentShaderDebug = std::move(stagedDebugFragmentShader);
	pRaw->m_rhiComputeShaderDebug = std::move(stagedDebugComputeShader);

	pRaw->m_colorAttachments = stagedColorAttachments;
	pRaw->m_depthStencilAttachment = stagedDepthStencilAttachment;

	if (!pRaw->IsReady())
	{
		SAILOR_LOG_ERROR(
			"UpdateRHIResource created an incomplete regular/debug shader set for shader %s permutation %u",
			pShader->GetFileId().ToString().c_str(),
			permutation);
		return false;
	}
	return true;
}

bool ShaderCompiler::LoadAsset(FileId uid, TObjectPtr<Object>& out, bool bImmediate)
{
	ShaderSetPtr outAsset;
	bool bRes = LoadShader_Immediate(uid, outAsset);
	out = outAsset;
	return bRes;
}

void ShaderCompiler::CollectGarbage()
{
	m_promises.LockAll();
	for (auto& promiseSet : m_promises)
	{
		RemoveFinishedPromiseEntries(promiseSet.m_second);
	}
	m_promises.UnlockAll();
}

#if defined(SAILOR_SHADER_CACHE_TEST_HOOKS)
bool ShaderCompilerTestAccess::AggregateCompileResults(const bool* results, size_t count)
{
	std::atomic_bool aggregate = true;
	for (size_t index = 0; index < count; ++index)
	{
		ShaderCompiler::RecordCompileResult(aggregate, results[index]);
	}
	return aggregate.load(std::memory_order_acquire);
}

bool ShaderCompilerTestAccess::SaveCacheAndCombineResult(
	ShaderCache& cache,
	bool bCompiledSuccessfully)
{
	return ShaderCompiler::SaveShaderCacheAndCombineResult(cache, bCompiledSuccessfully);
}

bool ShaderCompilerTestAccess::ShouldRetryCacheSave(
	size_t numPermutationsToCompile,
	bool bCacheDirty)
{
	return ShaderCompiler::ShouldRetryDirtyShaderCache(
		numPermutationsToCompile,
		bCacheDirty);
}

TVector<FileId> ShaderCompilerTestAccess::MergeShaderDependencyCandidates(
	const TVector<FileId>& parsedShaderIds,
	const TVector<FileId>& loadedShaderIds)
{
	return ShaderCompiler::MergeShaderDependencyCandidates(parsedShaderIds, loadedShaderIds);
}

std::string ShaderCompilerTestAccess::NormalizeShaderExtension(const std::string& filepath)
{
	return ShaderCompiler::NormalizeShaderExtension(filepath);
}

bool ShaderCompilerTestAccess::DoesShaderIncludePath(
	const TVector<std::string>& includes,
	const std::string& relativePath)
{
	return ShaderCompiler::DoesShaderIncludePath(includes, relativePath);
}

bool ShaderCompilerTestAccess::NormalizeShaderTabs(
	const std::string& extension,
	std::string& shaderText,
	std::string& outDiagnostic)
{
	return ShaderCompiler::NormalizeShaderTabs(extension, shaderText, outDiagnostic);
}

bool ShaderCompilerTestAccess::RewriteShaderSourceInPlace(
	const std::string& filepath,
	const std::string& expectedSource,
	const std::string& replacement,
	std::string& outDiagnostic)
{
	return ShaderCompiler::RewriteShaderSourceInPlace(
		filepath,
		expectedSource,
		replacement,
		outDiagnostic);
}

bool ShaderCompilerTestAccess::ReadShaderSourceBinary(
	const std::string& filepath,
	std::string& outSource,
	std::string& outDiagnostic)
{
	return ShaderCompiler::ReadShaderSourceBinary(filepath, outSource, outDiagnostic);
}

bool ShaderCompilerTestAccess::ExerciseFailedLoadEvictionAndRetry()
{
	constexpr uint32_t permutation = 7;
	FileId uid;
	uid.Deserialize(YAML::Node("{SHADER-COMPILER-FAILURE-LIFECYCLE}"));
	TConcurrentMap<FileId, TVector<TPair<uint32_t, uint32_t>>> promises;
	TConcurrentMap<FileId, TVector<TPair<uint32_t, uint32_t>>> shaders;
	{
		auto& promiseEntries = promises.At_Lock(uid);
		TConcurrentMapEntryUnlockGuard promisesUnlockGuard(promises, uid);
		auto& shaderEntries = shaders.At_Lock(uid);
		TConcurrentMapEntryUnlockGuard shadersUnlockGuard(shaders, uid);
		ShaderCompiler::AddShaderLoadEntries(
			promiseEntries,
			shaderEntries,
			permutation,
			101u,
			201u);
	}
	{
		auto& promiseEntries = promises.At_Lock(uid);
		TConcurrentMapEntryUnlockGuard promisesUnlockGuard(promises, uid);
		auto& shaderEntries = shaders.At_Lock(uid);
		TConcurrentMapEntryUnlockGuard shadersUnlockGuard(shaders, uid);
		ShaderCompiler::EvictFailedShaderLoadEntries(
			promiseEntries,
			shaderEntries,
			permutation);
	}
	{
		auto& promiseEntries = promises.At_Lock(uid);
		TConcurrentMapEntryUnlockGuard promisesUnlockGuard(promises, uid);
		auto& shaderEntries = shaders.At_Lock(uid);
		TConcurrentMapEntryUnlockGuard shadersUnlockGuard(shaders, uid);
		if (!promiseEntries.IsEmpty() || !shaderEntries.IsEmpty())
		{
			return false;
		}
		ShaderCompiler::AddShaderLoadEntries(
			promiseEntries,
			shaderEntries,
			permutation,
			102u,
			202u);
		return ShaderCompiler::FindPermutationIndex(promiseEntries, permutation) != static_cast<size_t>(-1) &&
			ShaderCompiler::FindPermutationIndex(shaderEntries, permutation) != static_cast<size_t>(-1);
	}

	return false;
}

bool ShaderCompilerTestAccess::ExercisePromiseGarbageCollection()
{
	TVector<TPair<uint32_t, Tasks::TaskPtr<ShaderSetPtr>>> promises;
	auto completed = Tasks::TaskPtr<ShaderSetPtr>::Make(ShaderSetPtr{});
	completed->Wait();
	promises.Add({ 1, completed });
	promises.Add({ 2, Tasks::TaskPtr<ShaderSetPtr>{} });
	ShaderCompiler::RemoveFinishedPromiseEntries(promises);
	return ShaderCompiler::FindPermutationIndex(promises, 1) == static_cast<size_t>(-1) &&
		ShaderCompiler::FindPermutationIndex(promises, 2) != static_cast<size_t>(-1);
}
#endif
