/*8*/
// Code is generated by Sailor Engine

// Vertex Attributes
#define DefaultPositionBinding 0
#define DefaultNormalBinding 1
#define DefaultTexcoordBinding 2
#define DefaultColorBinding 3
#define DefaultTangentBinding 4
#define DefaultBitangentBinding 5
#define DefaultBoneIdsBinding 6
#define DefaultBoneWeightsBinding 7

// Tile Lighting
#define LIGHTS_CULLING_TILE_SIZE 16
#define LIGHTS_CANDIDATES_PER_TILE 196
#define LIGHTS_PER_TILE 128

// GPU Culling
#define GPU_CULLING_GROUP_SIZE 256

// Shadows
#define MAX_SHADOWS_IN_VIEW 2048
#define MAX_SHADOW_MAP_SAMPLERS 128
#define MAX_TEXTURES_IN_SCENE 8192
#define NUM_CSM_CASCADES 4
const float ShadowMaxDistance = 200;
const float ShadowCascadeBlendFraction = 0.1;
const float ShadowCascadeLevels[4] = { 0.025,0.075,0.2,1};
