/*1*/
// Code is generated by Sailor Engine
#define LIGHTS_CULLING_TILE_SIZE 16
#define LIGHTS_CANDIDATES_PER_TILE 196
#define LIGHTS_PER_TILE 128
#define MAX_SHADOWS_IN_VIEW 1024
#define MAX_TEXTURES_IN_SCENE 262144
#define NUM_CSM_CASCADES 3
const float ShadowCascadeLevels[3] = { 0.04,0.2,0.5}; 
