function(run)
    execute_process(COMMAND ${ARGV} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "${ARGV}\n${output}\n${error}")
    endif()
endfunction()

function(build_identity output directory)
    run("${CMAKE_COMMAND}" --build "${directory}" --config Release --target InterfaceProbe)
    file(READ "${directory}/probe-path-Release.txt" probe)
    execute_process(COMMAND "${probe}" RESULT_VARIABLE result OUTPUT_VARIABLE identity OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "The compiled interface probe failed: ${result}")
    endif()
    set(${output} "${identity}" PARENT_SCOPE)
endfunction()

set(generator -G "${TEST_GENERATOR}")
if(TEST_PLATFORM)
    list(APPEND generator -A "${TEST_PLATFORM}")
endif()
foreach(copy IN ITEMS first relocated)
    set(root "${TEST_BINARY_DIR}/${copy}/sdk")
    file(MAKE_DIRECTORY "${root}/Runtime" "${root}/External")
    file(WRITE "${root}/Runtime/Component.h" "struct Component { int value; };\n")
    file(WRITE "${root}/External/YamlExceptionBoundary.h" "void Decode();\n")
    run("${CMAKE_COMMAND}" -S "${SAILOR_SOURCE_DIR}/Tests/WorkspaceInterface"
        -B "${TEST_BINARY_DIR}/${copy}/build" ${generator}
        "-DSAILOR_SOURCE_DIR=${SAILOR_SOURCE_DIR}" "-DSDK_ROOT=${root}" "-DINTERFACE_SETTINGS=PUBLIC_FLAG=1"
        -DCMAKE_BUILD_TYPE=Release)
endforeach()

set(build "${TEST_BINARY_DIR}/first/build")
set(root "${TEST_BINARY_DIR}/first/sdk")
build_identity(original "${build}")
build_identity(relocated "${TEST_BINARY_DIR}/relocated/build")
if(NOT original STREQUAL relocated)
    message(FATAL_ERROR "Relocating identical SDK inputs must preserve the interface identity")
endif()

file(WRITE "${root}/Runtime/Private.cpp" "void Implementation() {}\n")
build_identity(private_edit "${build}")
if(NOT original STREQUAL private_edit)
    message(FATAL_ERROR "Private implementation edits must not change the interface identity")
endif()

# No explicit reconfigure after header edits: an ordinary build must refresh the identity.
file(WRITE "${root}/Runtime/Component.h" "struct Component { double value; };\n")
build_identity(layout_edit "${build}")
if(original STREQUAL layout_edit)
    message(FATAL_ERROR "An engine layout change must change the interface identity")
endif()
file(WRITE "${root}/Runtime/Added.hpp" "struct Added {};\n")
build_identity(added "${build}")
if(layout_edit STREQUAL added)
    message(FATAL_ERROR "New public headers must contribute to the interface identity")
endif()
file(REMOVE "${root}/Runtime/Added.hpp")
build_identity(removed "${build}")
if(NOT layout_edit STREQUAL removed)
    message(FATAL_ERROR "Removing a public header must restore the previous identity")
endif()
file(WRITE "${root}/External/YamlExceptionBoundary.h" "bool Decode();\n")
build_identity(boundary_edit "${build}")
if(removed STREQUAL boundary_edit)
    message(FATAL_ERROR "Project-owned dependency boundary headers are part of the interface")
endif()

run("${CMAKE_COMMAND}" -S "${SAILOR_SOURCE_DIR}/Tests/WorkspaceInterface"
    -B "${build}" "-DINTERFACE_SETTINGS=PUBLIC_FLAG=2")
build_identity(settings_edit "${build}")
if(boundary_edit STREQUAL settings_edit)
    message(FATAL_ERROR "Public compile settings must contribute to the interface identity")
endif()
message(STATUS "Workspace interface identity and automatic rebuild contracts passed")
