name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  VCPKG_ROOT: ${{ github.workspace }}/External/vcpkg

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Cache vcpkg installed packages
      uses: actions/cache@v3
      with:
        path: |
          ${{ env.VCPKG_ROOT }}/installed
          ${{ env.VCPKG_ROOT }}/packages
        key: vcpkg-${{ runner.os }}-installed-${{ env.BUILD_TYPE }}
        restore-keys: |
          vcpkg-${{ runner.os }}-installed-

    - name: Run update_deps.bat
      shell: cmd
      run: .\update_deps.bat

    - name: Install Vulkan SDK  
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with:
        version: 1.3.275.0        
        cache: true

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: cmake --build build --config ${{ env.BUILD_TYPE }}

    - name: Test
      working-directory: build
      run: ctest -C ${{ env.BUILD_TYPE }}
