name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Install Vulkan SDK  
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with:
        version: 1.3.275.0        
        cache: true

    - name: Setup vcpkg and install dependencies
      id: vcpkg
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgArguments: install glm:x64-windows imgui[win32-binding]:x64-windows magic-enum:x64-windows nlohmann-json:x64-windows refl-cpp:x64-windows spirv-reflect:x64-windows stb:x64-windows tinygltf:x64-windows tracy:x64-windows yaml-cpp:x64-windows

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCMAKE_TOOLCHAIN_FILE=${{ steps.vcpkg.outputs.vcpkgToolchainFile }} -DVCPKG_TARGET_TRIPLET=x64-windows

    - name: Build
      run: cmake --build build --config ${{ env.BUILD_TYPE }}

    - name: Test
      working-directory: build
      run: ctest -C ${{ env.BUILD_TYPE }}
