name: Build Editor

on:
  workflow_dispatch:
  pull_request:

jobs:
  build-editor:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install MAUI workload
        run: dotnet workload install maui

      - name: Build Editor
        run: dotnet build Editor/SailorEditor.csproj -c Release
